import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import collectionsRouter from "./collections";
import gameRouter from "./game";
import weatherRouter from "./weather";
import googleRouter from "./google";
import playerStateRouter from "./player-state";
import multiplayerRouter from "./multiplayer";
import authRouter from "./auth";
import integrateSystemRouter from "./integratesystem";
import supremeRouter from "./supreme";
import agentRouter from "./agent";
import auroraToolingRouter from "./aurora-tooling";
import mcpRouter from "./mcp";
import operatorRouter from "./operator";
import invistaSessionRouter from "./invista-session";
import derivRouter from "./deriv";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(collectionsRouter);
router.use(gameRouter);
router.use(weatherRouter);
router.use(googleRouter);
router.use(playerStateRouter);
router.use(multiplayerRouter);
router.use(authRouter);
router.use(supremeRouter);
router.use(integrateSystemRouter);
router.use(auroraToolingRouter);
router.use(mcpRouter);
router.use(operatorRouter);
router.use(invistaSessionRouter);
router.use(derivRouter);
router.use(agentRouter);

export default router;
